# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
  - cron: "0 2 * * 1-5"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4
      - name: GitHub Script
      - uses: actions/github-script@v4.0.2
        with:
          # The script to run
          script: |
             console.log(context)
          # Whether to tell the GitHub client to log details of its requests
          debug: true
